spring.application.name=springpoo
logging.config=classpath:log4j2.xml
logging.level.com.sena.springpoo=DEBUG

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/springpoo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.mvc.hiddenmethod.filter.enabled=true

# N8N webhook URL
# MODO TEST  (solo funciona cuando n8n esta escuchando activamente)
# n8n.webhook.url=https://jeronimogil.app.n8n.cloud/webhook/Archivos
# MODO PRODUCCION (activar el workflow en n8n y usar esta)
n8n.webhook.url=https://jeronimogil.app.n8n.cloud/webhook/Archivos

# Tamano maximo de archivo (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
